version: '3.8'

services:
  # MediaMTX WebRTC streaming service
  mediamtx:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MTX_PROTOCOLS=udp
      - MTX_WEBRTCADDITIONALHOSTS=89.46.131.17
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
      - "9997:9997"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
    networks:
      - media_network
    

  # Coturn STUN/TURN server for WebRTC
  coturn:
    image: instrumentisto/coturn
    container_name: coturn-server
    ports:
      - "3478:3478"     # STUN/TURN port
      - "3478:3478/udp" # STUN/TURN port (UDP)
      - "5349:5349"     # TURNS (TLS) port
    environment:
      - EXTERNAL_IP=89.46.131.17 
    command:
      - turnserver
      - --no-auth
      - --realm=example.com
      - --no-dtls
      - --no-tls
      - --log-file=/var/log/turnserver.log
      - --verbose

    networks:
      - media_network

networks:
  media_network:
    driver: bridge
